---
title: "Analysis of crop data"
author: "G. Marchetti"
date: "21 03 2024"
format: 
  html:
    embed-resources: true
  pdf:
    documentclass: scrartcl
    number-sections: false
    colorlinks: true
    include-in-header: 
      text: | 
        \usepackage[default]{fontsetup} 
---

```{=tex}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\setmathfont{NewCMMath-Regular.otf}
\newcommand{\ci}{\hspace{0.1em}\perp\hspace{-0.95em}\perp\, }
\renewcommand{\b}[1]{\boldsymbol{#1}}
```
```{r}
#| message: false
source("~/Documents/R_packages/cat_regression_chains/RCG/funs_RCG.R")
library("bnlearn") 
library("ggm")
library(mnormt)
```

```{r}
#| cache: true
```

Read the data

```{r}
#| fig-width: 5
#| fig-height: 5
setwd("~/Documents/Talks/Firenze PhD 2024/")
crop <- read.table("cropdata.txt", header = TRUE)
crop <- data.frame(crop)
pairs(crop, pch = '.')
```


```{r}
#| fig-height: 3
#| fig-width: 3
G <- DAG(C ~ S + W, S ~ V, W ~ V, V ~ G + E)
G
drawGraph(G)
```


## Fit of the first equation

```{r}
m_full1<- lm(C ~ S+W+V+G+E, data = crop)
round(summary(m_full1)$coef,3)
m_red1 <- lm(C ~ S + W, data = crop)
anova(m_red1, m_full1, test = "F")
```


### LR test (asymptotic)     

```{r}
#| include: false
ci_test("C", c("V","G","E"), c("S", "W"), test = "mi-g", data = crop)
```

```{r}
`LRtest` <- function(m_red, m_full) {
l0 <- logLik(m_red)[1]
lsat <- logLik(m_full)[1]
w <- 2 * (lsat - l0)
df <- m_red$df.residual - m_full$df.residual
p <- 1 - pchisq(w, df)
c(w = w, df = df, p = p)
}
```

```{r}
LRtest(m_red1, m_full1)
```
### Second equation

```{r}
m_full2 <- lm(S ~ W + V + G + E, data = crop)
round(summary(m_full2)$coef,3)
m_red2 <- lm(S ~ 1, data = crop)
anova(m_red2, m_full2, test = "F")
```

### LR test

```{r}
LRtest(m_red2, m_full2)
```

### Third equation

```{r}
m_full3 <- lm(W ~ V + G + E, data = crop)
round(summary(m_full3)$coef,3)
m_red3 <- lm(W ~ V, data = crop)
anova(m_red3, m_full3, test = "F")
```
### LR test

```{r}
LRtest(m_red3, m_full3)
```

### Fourth equation 

```{r}
m_full4 <- lm(V ~ G + E, data = crop)
round(summary(m_full4)$coef,3)
m_red4 <- m_full4
```

### Last equation 
```{r}
m_full5 <- lm(G ~ E, data = crop)
round(summary(m_full5)$coef,3)
m_red5 <- lm(G ~ 1, data = crop)
anova(m_red5, m_full5, test = "F")
```


### LR test

```{r}
LRtest(m_red5, m_full5)
```


## Fit DAG
```{r}
ord <- colnames(G)
S <- cov(crop[,ord])
lapply(fitDag(G, S, n= 200), function(x) round(x,3))
```
