---
title: "Graphs in R"
author: "G. Marchetti"
date: "May 13 2024"
format: 
  html:
    embed-resources: true
  pdf:
    documentclass: scrartcl
    number-sections: true
    colorlinks: true
---
$\newcommand{\ci}{\,\perp\!\!\!\perp\,}$

```{=tex}
\setkomafont{disposition}{\Large\sffamily}
\renewcommand{\b}[1]{\boldsymbol{#1}}
\newcommand{\ci}{\,\perp\!\!\!\perp\,}
```
```{r}
#| include: false
#| message: false
source("~/Documents/R_packages/cat_regression_chains/RCG/funs_RCG.R")
library("bnlearn") 
library("ggm")
library("gRbase")
library("igraph")
```

# Using  `ggm`,  `grBase`, `igraph` together

Using **gRbase**

Adjacency matrix $X \ci Y$
```{r}
A <- ug(~a*b, ~b*c*d, ~e) 
as(A, "matrix") 
```

Using **ggm**

Adjacency matrix and plot
```{r}
#| fig-width: 4
#| fig-height: 4
#| out-width: "50%" 
G <- UG(~a*b + b*c*d + e)
G
drawGraph(G, layout = layout_nicely)
```

# Find cliques

With **gRbase*
```{r}
get_cliques(A)
```

# Separation

With **ggm** and **igraph**
```{r}
#| fig-width: 4
#| fig-height: 3
#| out-width: "50%" 
G <- UG( ~ x1*x3*x4 + x2*x3*x5 + x3*x4*x5)
drawGraph(G, layout = layout_nicely)
```
With **gRbase** and **igraph**

```{r}
g <- graph_from_adjacency_matrix(G, mode = "undirected")
separates("x5", "x1", "x4", g)
```

```{r}
separates("x5", "x1", c("x4","x3"), g)
```

```{r}
get_cliques(g)
```

# Exercise

Lauritzen's graph

```{r}
G <- UG(~ x1*x2 + x2*x5 + x5*x3 + 
           + x1*x3 + x2*x4 + x4*x7 +
           + x7*x5 + x3*x6 + x5*x6 + x7*x6)
drawGraph(G, layout = layout_nicely)
```

# Plot with ggm

```{r}
#| fig-width: 4
#| fig-height: 3
#| out-width: "50%" 
source("~/Documents/R_packages/ggm/plotGraph2.R")
D <- makeMG(dg = DAG(x2 ~ x1 + xH, x3 ~ x2 + xH))
options(repr.plot.width = 4, repr.plot.height = 4)
sg <- SG(D, M = "xH") 
plotGraph2(sg, tcltk = FALSE, dashed = FALSE)
```

$$
\begin{array}{|c|c|}\hline
Age & Frequency \\ \hline
18-25  & 15 \\
26-35  & 33 \\
36-45  & 22 \\ \hline
\end{array}
$$

```{r}
#| echo: false
#| message: false
#| fig-cap: "A directed acyclic graph."

library(DiagrammeR)
library(DiagrammeRsvg)  # for conversion to svg
library(rsvg)           # for saving svg
G <- DiagrammeR::grViz("
  digraph mrdag {
  graph [rankdir=TB]

  node [shape=ellipse]
  U [label='Confounders']

  node [shape=box, height=0.3, width=0.3]
  G [label='Genotype']
  X [label='Phenotype']
  Y [label='Outcome']
  { rank = same; G X Y }

  G -> X [minlen=3]
  U -> X
  U -> Y
  X -> Y [minlen=3]
  }
  ", height = 150)
```

